# -*- coding: utf-8 -*-
# Generated by Codex for pipeline diagnostics initial models.

from django.db import migrations, models
import django.db.models.deletion
import pipeline.contrib.diagnostics.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticEvent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=64, unique=True, verbose_name="诊断事件ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[("stuck", "执行卡住"), ("exception", "执行异常")],
                        db_index=True,
                        max_length=32,
                        verbose_name="诊断事件类型",
                    ),
                ),
                ("source", models.CharField(max_length=64, verbose_name="诊断来源")),
                ("pipeline_id", models.CharField(db_index=True, max_length=64, verbose_name="Pipeline ID")),
                ("node_id", models.CharField(blank=True, db_index=True, default="", max_length=64, verbose_name="节点ID")),
                ("process_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="进程ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("processing", "处理中"), ("processed", "已处理"), ("ignored", "已忽略")],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="处理状态",
                    ),
                ),
                ("detail", pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="诊断详情")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "Pipeline诊断事件",
                "verbose_name_plural": "Pipeline诊断事件",
                "ordering": ["-id"],
                "index_together": {("pipeline_id", "node_id"), ("status", "created_at")},
            },
        ),
        migrations.CreateModel(
            name="DiagnosticCase",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("case_id", models.CharField(max_length=64, unique=True, verbose_name="诊断案例ID")),
                ("pipeline_id", models.CharField(db_index=True, max_length=64, verbose_name="Pipeline ID")),
                ("node_id", models.CharField(blank=True, db_index=True, default="", max_length=64, verbose_name="节点ID")),
                ("process_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="进程ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "待治理"), ("handled", "已治理"), ("closed", "已关闭")],
                        db_index=True,
                        default="open",
                        max_length=32,
                        verbose_name="治理状态",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "提示"), ("warning", "告警"), ("critical", "严重")],
                        db_index=True,
                        default="info",
                        max_length=32,
                        verbose_name="严重级别",
                    ),
                ),
                (
                    "diagnosis",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="诊断结论"),
                ),
                (
                    "suggestion",
                    pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="治理建议"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="diagnostics.DiagnosticEvent",
                        verbose_name="诊断事件",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline诊断案例",
                "verbose_name_plural": "Pipeline诊断案例",
                "ordering": ["-id"],
                "index_together": {("pipeline_id", "node_id"), ("status", "severity")},
            },
        ),
        migrations.CreateModel(
            name="DiagnosticOperationAudit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operator", models.CharField(max_length=64, verbose_name="操作人")),
                (
                    "operation",
                    models.CharField(
                        choices=[("retry", "重试"), ("resume", "恢复"), ("ignore", "忽略")],
                        db_index=True,
                        max_length=32,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        db_index=True,
                        max_length=32,
                        verbose_name="操作状态",
                    ),
                ),
                ("request", pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="操作请求")),
                ("result", pipeline.contrib.diagnostics.models.JSONTextField(default=dict, verbose_name="操作结果")),
                ("message", models.TextField(blank=True, default="", verbose_name="操作信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_audits",
                        to="diagnostics.DiagnosticCase",
                        verbose_name="诊断案例",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline诊断操作审计",
                "verbose_name_plural": "Pipeline诊断操作审计",
                "ordering": ["-id"],
                "index_together": {("operator", "operation"), ("status", "created_at")},
            },
        ),
    ]
